### ISSUE TITLE
Duplicate agent profile images being added every day

### ISSUE THREAD

**Issue by vinnylabarbera** [agentevolution/impress-agents#2]
It looks like a new profile image is being added to the WordPress media library every day when agents are imported.

https://www.evernote.com/l/AArQrbdTx1NFKYtvsAJ9Px23wvsRqeMEkx0

**Comment by davebonds** [comment]
Thanks we're looking into this.

**Comment by bhubbard** [comment]
@davebonds Can we get an update on this?

**Comment by davebonds** [comment]
This was resolved in v1.0.1
